### ISSUE TITLE
Limit categories per archive: not working

### ISSUE THREAD

**Issue by denbue** [codefog/contao-news_categories#103]
When I edit or create a news archive I have the option to limit the available categories to this archive. Unfortunately the function is not working for me: When I select a category, hit the confirm button, the selection is not saved.

Contao: 3.5.25
Plugin: 2.8.1
Tested in Firefox and Safari.

Console shows error: ```ReferenceError: Can't find variable: Theme```

Screenshot: 

![screen shot 2017-04-23 at 21 58 29](https://cloud.githubusercontent.com/assets/2946670/25316976/8212252e-2870-11e7-9b44-ce8a182f2857.jpg)

**Comment by denbue** [comment]
Actually the issue happens every time the modal to select a category opens.

**Comment by qzminski** [comment]
What is your `widget_tree_picker` version? What way have you installed the extensions (ER, Composer, manually) ?

**Comment by denbue** [comment]
I installed the extension through composer (codefog/contao-news_categories) and my treepicker version is 2.3.2.

Also, other browser plugins like Adblock etc are deactivated.

**Comment by qzminski** [comment]
Hmm what errors do you get in the JS console? Looks like as if the assets have not been loaded at all.

**Comment by denbue** [comment]
These are the errors I get:

![image](https://cloud.githubusercontent.com/assets/2946670/25352774/712fea9e-292d-11e7-8f55-f754d34529c9.png)

**Comment by fritzmg** [comment]
Your assets are causing a fatal error. Look at the responses for those asset URLs.

**Comment by qzminski** [comment]
@denbue can you open the full response and check what fatal error you get there?

**Comment by denbue** [comment]
When I click on one of the errors, I only get this message:

```No Javascript on this page
If <script> tags have a "type" attribute, it should equal "text/javascript" or "application/javascript". Also scripts must be parsable (syntactically correct).```

The page is currently only in testing, so if it helps I could give access to the backend.

**Comment by qzminski** [comment]
Can you open any of those files in a new browser tab? It should display the full error message then.

**Comment by denbue** [comment]
Yes, thats more clear.

```
Fatal error: Uncaught exception Exception with message The table name must not be empty thrown in system/modules/core/library/Contao/DcaLoader.php on line 48

#0 system/modules/core/library/Contao/Controller.php(1312): Contao\DcaLoader->__construct(NULL)
#1 system/modules/widget_tree_picker/public/treepicker.php(97): Contao\Controller::loadDataContainer(NULL)
#2 system/modules/widget_tree_picker/public/treepicker.php(141): TreePicker\TreePicker->run()
#3 {main}
```

**Comment by qzminski** [comment]
I have just installed the extension through the composer as well and it works all fine. There must be something wrong with your server configuration because including e.g. the `treepicker.min.js` file can't return a PHP fatal error – this is not a PHP file.

**Comment by fritzmg** [comment]
If the file is not found by he server, Contao's catch all route shows the not found error.
