### ISSUE TITLE
Contao 4: only 2 categories are displayed

### ISSUE THREAD

**Issue by fritzmg** [codefog/contao-news_categories#106]
I have added several categories under _News_ » _News-categories_ and they are visible in the database:

![nc](https://cloud.githubusercontent.com/assets/4970961/26828822/67ecc54e-4ac3-11e7-9ca2-b4d496425ef7.png)

However, only 2 are displayed:

![nc2](https://cloud.githubusercontent.com/assets/4970961/26828851/823de798-4ac3-11e7-8a49-9d7c00399a95.png)

The picker shows them all though:

![ncp](https://cloud.githubusercontent.com/assets/4970961/26828920/bb11ae88-4ac3-11e7-9a65-0b7a1c623138.png)

Tested in Contao `4.3.11`.

**Comment by fritzmg** [comment]
The problem is caused by this line: [contao/core-bundle/blob/4.3.11/src/Resources/contao/drivers/DC_Table.php#L3525](https://github.com/contao/core-bundle/blob/4.3.11/src/Resources/contao/drivers/DC_Table.php#L3525)
```php
$this->root = $this->eliminateNestedPages($arrFound);
```
The `$strTable` parameter is missing, thus this function automatically checks against `tl_page` instead of `tl_news_category`, which makes no sense of course. When you change it to
```php
$this->root = $this->eliminateNestedPages($arrFound, $table);
```
for example, everything will be fine.

**Comment by fritzmg** [comment]
PR: https://github.com/contao/core-bundle/pull/863

**Comment by qzminski** [comment]
So this is a Contao bug and we can close this issue?

**Comment by fritzmg** [comment]
Yes. However, if the PR is rejected, I'll reopen if necessary.
