### ISSUE TITLE
Contao 4.4: error for user(s) while loging-in

### ISSUE THREAD

**Issue by jankout** [codefog/contao-news_categories#108]
Hello, there are some errors with the extension in the current version of Contao. 

See https://github.com/contao/core/issues/8734

Could you fix it, please? Thank you.

**Comment by fritzmg** [comment]
This issue also occurs in Contao 3.x btw. Currently the option __Manage news categories__ is meaningless still it always leads to `true` for any user (or it results in an SQL exception).

**Comment by qzminski** [comment]
Hey guys can you try 2fb3b6f? You must update the database and set the permissions again.

**Comment by jankout** [comment]
Thank you. I'm sorry but I cannot try it because the website is in a productive modus. I will be waiting for the new version. Please, let me know. Thank you.

**Comment by qzminski** [comment]
@fritzmg do you mind maybe? 😉

**Comment by fritzmg** [comment]
Already working on it ;)

**Comment by fritzmg** [comment]
Hm, for some reason composer does not let me install that hotfix with
```
composer require codefog/contao-news_categories dev-hotfix/2.8.4
```
```
  [InvalidArgumentException]
  Could not find package dev-hotfix/2.8.4 at any version for your minimum-stability (dev). Check the package spelling
   or your minimum-stability
```
Should be the correct branch, should it not?

**Comment by qzminski** [comment]
Yeah that should do. No idea what exactly is causing that exception though 😳

**Comment by fritzmg** [comment]
I have tested it in Contao 3.5.27 and everything worked as expected :). Should be fine in Contao 4.x too.

**Comment by qzminski** [comment]
Thanks for confirmation, I am releasing a new version then.

**Comment by jankout** [comment]
Thank you for your quick and great work.
