### ISSUE TITLE
Suggestion: Event Categories

### ISSUE THREAD

**Issue by jankout** [codefog/contao-news_categories#110]
Hello, 

I would like to ask you whether you will be interested to make a similar extension for events? It would be great. Or if you want and teach me how to make it, I can make it by myself. Thank you.

**Comment by qzminski** [comment]
Hey Jan, I have this in plans but I always lack the time to do it... I have to rewrite the news_categories first anyway. The plans for the new version also require the adjustments in the Contao bundles so it's a pretty big topic. Nevertheless any help or sponsorship would be very welcome.

**Comment by fritzmg** [comment]
I may be able to develop something for events using similar concepts as news_categories (i.e. using the widget tree picker and saving the categories the same way as news_categories does). There is already a categories extension for events though: https://github.com/marebe1602/mae_event_categories
But it lacks features like hierarchical categories for example.

**Comment by jankout** [comment]
@fritzmg It would be great. Would you like to do it soon? If I could help you somehow, please, let me know.

**Comment by fritzmg** [comment]
Unfortunately as it turns out we won't be needing this in one of our current projects after all, so I won't have time to implement this.

**Comment by qzminski** [comment]
Thanks @akroii , but I think I'd have to raise some crowdfunding for this project, as this seems to be quite a lot of effort. If that ever happens I will let you know 🙂
