### ISSUE TITLE
Contao 4.4: news_resetCategories cannot be clicked

### ISSUE THREAD

**Issue by fritzmg** [codefog/contao-news_categories#111]
If you create a `newscategories` module, the checkbox for `news_resetCategories` cannot be clicked, because it is overlayed by the following `news_showQuantity` field.

May be the `tl_module` DCA of `news_categories` should add `'tl_class'=>'w50'` to `news_showQuantity`.

**Comment by qzminski** [comment]
Sounds like the Contao core BC break? I had the similar problems with `dlh_googlemaps` for example. I'll fix it anyway, should be much faster even if it's really a Contao bug 🙂

**Comment by fritzmg** [comment]
Yeah I remember this being reported somewhere else. I haven't look too much into it yet.

**Comment by qzminski** [comment]
Fixed in 4302e50.
