### ISSUE TITLE
Problems with "News archive menu" - Version 2.8.5

### ISSUE THREAD

**Issue by Total-Reality** [codefog/contao-news_categories#113]
Hey,

you have a bug in the line 238 @ModuleNewsMenu.php

`$strUrl = \Environment::get('request');`

This results in duplicate entries of "?" in the url if you use a "News archive menu" on the same page as "News categories list".

Wrong links generated because of your module e.g.:
news-list-archiv.html?month=201702?month=201410
news-list-archiv.html?month=201702?month=201411

Correct links:
news-list-archiv.html?month=201410
news-list-archiv.html?month=201411

You can fix it with code like it follows:

```
$strUrl = \Environment::get('request');

if(stristr(\Environment::get('requestUri'), '?'))
{
  $strUrl = strstr(\Environment::get('request'), '?', true);
}
```

It would be great if you can fix this.

Best regards,
Chris

**Comment by qzminski** [comment]
Fixed in a2aa0c4.
