### ISSUE TITLE
URL Encoded value "%2F"

### ISSUE THREAD

**Issue by WebNetCrea** [codefog/contao-news_categories#124]
Hi,

I have "%2F" instead of / in the URL of the news categories menu.

It's a bug ?

Thx

**Comment by qzminski** [comment]
Hey, what version of the extension have you got installed?

**Comment by WebNetCrea** [comment]
news_categories | 2.8.7   & Contao 3.5.31

**Comment by qzminski** [comment]
Should be fixed in 0b41ea9. I have also released a new version in Contao ER.

**Comment by WebNetCrea** [comment]
Work's fine Thx :)
