### ISSUE TITLE
reduce CSS classes

### ISSUE THREAD

**Issue by fritzmg** [codefog/contao-news_categories#127]
Currently the extension adds the `news_category_X` and `category_X` classes in the `parseArticles` hook for each category of the news article. This bloats the page with CSS classes, especially on large news lists and when the news entries have multiple categories.

How about just `cat_X` instead? Similar to the `arc_X` class of the `contao/news-bundle`.

**Comment by qzminski** [comment]
Does it really bloat your page size that much? I have preserved those CSS classes because of BC reasons.

**Comment by fritzmg** [comment]
> Does it really bloat your page size that much?

May be it's just a matter of taste ;). I noticed it in one installation where each news article has between 2 and 4 categories and in the latest news list showing the last 20 news articles there would be between 80 and 160 css classes related to the categories. Half of which are redundant of course.

> I have preserved those CSS classes because of BC reasons.

Yeah, I thought so. Anyway, I still think using `cat_X` would be more consistent, since the core also uses something similar for the archive class. But I understand if this can only be added in `4.0.0`, if at all.

**Comment by qzminski** [comment]
> But I understand if this can only be added in 4.0.0, if at all.

Exactly and that is not coming soon, so I will close the issue for now.

**Comment by qzminski** [comment]
`news_category_n` is the same as `category_n` see: https://github.com/codefog/contao-news_categories/blob/master/src/Model/NewsCategoryModel.php#L65-L66

I can't remove either because that would be a BC break.
