### ISSUE TITLE
Can't select more than one category

### ISSUE THREAD

**Issue by cgpro** [codefog/contao-news_categories#130]
It happens in the module list with news categories. I change the selection of the news categories and click apply in the lightbox. After this only an activity indicator shows ups and the selection is not applied, only the first option is applied, if I save the module.

In the JS console is the following log:
treepicker.min.js:1 
contao/main.php?do=themes&table=tl_module&act=edit&id=16&rt=5a99e295012903fae7f40e3bbccec8b8&ref=d92ea93e 500 (Internal Server Error)

It happens with Apache and NGINX. With MAMP and the standard settings of domainfactory.de. I've updated Contao to 3.5.31 and I'm using news categories 2.8.8

**Comment by fritzmg** [comment]
Is there an entry in the error.log?

**Comment by cgpro** [comment]
[16-Jan-2018 07:42:29 Europe/Berlin] PHP Fatal error: Uncaught exception 'Error' with message 'Class 'HeimrichHannot\Ajax\Ajax' not found' thrown in /Applications/MAMP/htdocs/_archive/...system/modules/multifileupload/forms/FormMultiFileUpload.php on line 143
#0 /Applications/MAMP/htdocs/_archive/...system/modules/multifileupload/widgets/BackendMultiFileUpload.php(24): HeimrichHannot\MultiFileUpload\FormMultiFileUpload->__construct(Array)
#1 /Applications/MAMP/htdocs/_archive/...system/modules/core/library/Contao/System.php(140): HeimrichHannot\MultiFileUpload\Widget\BackendMultiFileUpload->__construct()
#2 /Applications/MAMP/htdocs/_archive/...system/modules/core/classes/Ajax.php(467): Contao\System->import('HeimrichHannot\\...')
#3 /Applications/MAMP/htdocs/_archive/...system/modules/core/classes/Ajax.php(450): Contao\Ajax->executePostActionsHook(Object(Contao\DC_Table))
#4 /Applications/MAMP/htdocs/_archive/...system/modules/core/classes/Backend.php(414): Contao\Ajax->executePostActions(Object(Contao\DC_Table))
#5 /Applications/MAMP/htdocs/_archive/...system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('themes')
#6 /Applications/MAMP/htdocs/_archive/...contao/main.php(20): Contao\BackendMain->run()
#7 {main}

**Comment by cgpro** [comment]
It worked some months ago. Maybe is Ajax uninstalled via a composer update?

**Comment by qzminski** [comment]
I looks like an error of `multifileupload` and not `news_categories` extension.

**Comment by cgpro** [comment]
Ok thanks. I'll continue here: https://github.com/heimrichhannot/contao-multifileupload/issues
