### ISSUE TITLE
Related Categories – only filter by specific categories

### ISSUE THREAD

**Issue by rustykowski** [codefog/contao-news_categories#134]
I have a taxonomy of 2 branches (main categories) and several sub-categories.
I would like to display related news of only 1 category-branch. Is it possible to configure the frontend module to do that?

**Comment by qzminski** [comment]
That's currently not supported but I will add it to the feature roadmap.

**Comment by rustykowski** [comment]
okay, thank you. That would be great!

**Comment by qzminski** [comment]
Implemented in a34595b.

**Comment by rustykowski** [comment]
Thanks a lot, qzminski! It's less than a year, that i opened this feature-request ;-)

**Comment by qzminski** [comment]
Yeah well, work on open source can be really exhaustive sometimes 😉
