### ISSUE TITLE
Tree picker on news edit keeps showing disabled categories

### ISSUE THREAD

**Issue by rocchidavide** [codefog/contao-news_categories#135]
I have some categories disabled, but when I go to "edit news" and I click on the button to change categories, tree picker shows also the disabled categories.

Contao version: 3.5.12
News Category version: 2.7.2 version 1

Thank you

**Comment by fritzmg** [comment]
That's normal. Publishing/Unpublishing generally only affects the front end, not the back end.

**Comment by rocchidavide** [comment]
Could be useful to show only enabled categories also in backend: imagine a team of editors and hundreds of categories, how can they know which categories they can use?

**Comment by fritzmg** [comment]
You can limit the categories for each user or group.

**Comment by rocchidavide** [comment]
Hey, this is a good idea! Thank you

**Comment by qzminski** [comment]
Just like @fritzmg suggested, that's the way to go.
