### ISSUE TITLE
Redirect to parent page if page not found

### ISSUE THREAD

**Issue by akroii** [codefog/contao-news_categories#136]
Hi codefog,
in my case, there's a category-list in footer.
If I try to force 404 `xxxx.org/parent/subpage-sdiofsdf` I will be redirected to parent page.

If I delete the module in footer, everything works.

Contao 4.4.13
php 7.1.18
news-categories: 3.0.7

**Comment by qzminski** [comment]
Are you talking about the `News categories list` frontend module? That would be really strange because it does not do any redirects...

**Comment by qzminski** [comment]
I have just released 3.0.8 which fixes the issue.
