### ISSUE TITLE
Error while updating to version 3.0.10 on contao-4.5.6

### ISSUE THREAD

**Issue by bizon1** [codefog/contao-news_categories#141]
I'm using contao-4.5.6 width contao-news_categories 3.0.9.
Everything is working perfect.

During a composer update contao-news_categories will be updated to version 3.0.10.
This leads to the following error:
`> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
PHP Fatal error:  Declaration of Codefog\NewsCategoriesBundle\Picker\NewsCategoriesPickerProvider::getUrl(Contao\CoreBundle\Picker\PickerConfig $config) must be compatible with Contao\CoreBundle\Picker\AbstractPickerProvider::getUrl(Contao\CoreBundle\Picker\PickerConfig $config): ?string in /datadisk/www/testing/vendor/codefog/contao-news_categories/src/Picker/NewsCategoriesPickerProvider.php on line 17
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception                                                         
  [RuntimeException]                                                                                         
  An error occurred while executing the "contao:install-web-dir" command: PHP Fatal error:  Declaration of Codefog\NewsCategoriesBundle\Picker\NewsCategoriesPickerProvider::getUrl(Contao\CoreBundle\Picker\PickerConfig $config) must be compatible with Contao\CoreBundle\Picker\AbstractPickerProvider::getUrl(Contao\CoreBundle\Picker\PickerConfig $config): ?string in /datadisk/www/testing/vendor/codefog/contao-news_categories/src/Picker/NewsCategoriesPickerProvider.php on line 17`

Switching back to version 3.0.9 the error message disappears and it is working well again.

**Comment by qzminski** [comment]
For now we have to see what will be the conclusion for https://github.com/contao/core-bundle/issues/1455.

**Comment by qzminski** [comment]
This is a contao/core-bundle issue and should be gone when you update the system to 4.5.7.
