### ISSUE TITLE
Hide Categories in news (in tl_news)

### ISSUE THREAD

**Issue by DVeris** [codefog/contao-news_categories#142]
Hide unpublished category in news.

$GLOBALS['TL_DCA']['tl_news']['fields']['categories']

**Comment by fritzmg** [comment]
Any publish/unpublish/visible/invisible functionality in Contao is for the front end, not the back end.

**Comment by qzminski** [comment]
Exactly.

**Comment by DVeris** [comment]
how to disable categorie in backend? (not delete)

**Comment by fritzmg** [comment]
Duplicate of https://github.com/codefog/contao-news_categories/issues/135
