### ISSUE TITLE
Error "Unknown insert tag {{news_categories::frontendTitle}}"

### ISSUE THREAD

**Issue by Y-Nell** [codefog/contao-news_categories#143]
Hi Kamil,

after updating to Contao 4.4.18 I got an "Unknown insert tag {{news_categories::frontendTitle}}" error in the System-Log. My installed extension version is 2.8.10.

Ironically I see no problem in the FE.

Any idea?

**Comment by qzminski** [comment]
Version 2.x is no longer supported, please use version 3.x instead.
