### ISSUE TITLE
News categories in backend not visible or shown multiple times in news

### ISSUE THREAD

**Issue by thepixture** [codefog/contao-news_categories#144]
I have 5 main news-categories with sub categories inside:
![image](https://user-images.githubusercontent.com/1543896/42509418-12488cae-844c-11e8-9d42-9603c5abeaca.png)

Inside of a news archive i assign the main category "eMag Categories - DE". If i then add a news and click on categories, i get this:
![image](https://user-images.githubusercontent.com/1543896/42509583-a6793cca-844c-11e8-84cd-982ac9cc791b.png)

I also assigned the category "Career level - DE" to this archive, but this is not shown up inside of the news.

Lot of strange things are happen.

**Comment by asaage** [comment]
might be related to https://github.com/codefog/contao-news_categories/issues/137
I have the same experience sometimes.

@thepixture it doesn't solve that problem but in your case i would probably use the [multilingual-features](https://github.com/codefog/contao-news_categories/blob/master/docs/multilingual-features.md)

**Comment by thepixture** [comment]
Thanks for the link. But at this point i've no more time to change the category stuff.
I finally did not restrict the categories for the news archives. That's how it works.
Maybe i'll try your linked extension in the next project.

**Comment by qzminski** [comment]
Hey @thepixture are you on the latest News Categories 3.0.10 version? Would you be able to send me your SQL dump?

**Comment by reluem** [comment]
same for me. 
Restrictions in the news archives lead to a shorter/incomplete list of categories in the news item settings.

**Comment by qzminski** [comment]
Guys as I am unable to reproduce this with my local setup and thus I need your database dumps (can only be the `tl_news_*` tables) to fix this issue :wink:

**Comment by qzminski** [comment]
This problem is very likely caused by https://github.com/contao/contao/pull/44
