### ISSUE TITLE
Insert Tag for Category Image

### ISSUE THREAD

**Issue by rburch** [codefog/contao-news_categories#147]
Not sure if this is a bug or an enhancement suggestion. I tried using tag: {{news_categories::image}} to pull the category image. It sort of works but I'm not getting the image, I'm getting a bunch of funny characters.

**Comment by qzminski** [comment]
Fixed in 3.0.11 which has been released now. Now you can use it with combination of genuine Contao insert tag for image, e.g. `{{image::{{news_categories::image}}}}`.

**Comment by rburch** [comment]
Works great!!
