### ISSUE TITLE
Contao 4.6.0-RC1 and contao-news_categories

### ISSUE THREAD

**Issue by squidi** [codefog/contao-news_categories#148]
works fine with contao 4.4 / 4.5 but with 4.6.0-RC1 it is not possible to start news in in the BE

> Attempted to load class "codefog_news_categories.listener.data_container.feed" from the global namespace. Did you forget a "use" statement?

**Comment by qzminski** [comment]
This Contao version is not stable and thus I can't provide any support for it yet.

**Comment by squidi** [comment]
Sorry but this answer is unsatisfactory. No wonder nobody tests rc-versions anymore before the final is released.

I'am not amused :(

**Comment by fritzmg** [comment]
Are you using Symfony 3 or 4?

**Comment by qzminski** [comment]
Unfortunately the open source is so exhausting I am not able to test the extension under every Contao version that is being released and thus the policy is set to test it only for stable versions. At first sight it looks like a BC break which is a bug and that's another reason I want to wait for the first stable release.
