### ISSUE TITLE
[BUG] User categories without rights to manage categories

### ISSUE THREAD

**Issue by fh1601com** [codefog/contao-news_categories#154]
Hi, 

thank you for the useful extension at first. We are in general quite happy to use it, but seem to have found a small bug now. 

## 
**Choosing a news category without the right to manage categories**
What we want to do here is to give a user-group the rights to assign categories to news. At the same time the user-group should not be allowed to modify these news categories. If we don't check the "manage" option, our user-group cannot set categories for news, as the DC-Picker is greyed out.
Perhaps a better solution would be to display a (draggable) checkbox-list instead of the disabled DC picker.

##
**Screenshots**

![image](https://user-images.githubusercontent.com/40591341/47782930-b8353280-dd01-11e8-8c9c-0155b748dac6.png)
![image](https://user-images.githubusercontent.com/40591341/47783009-f0d50c00-dd01-11e8-83b5-17802454b799.png)

## 
Maybe there is an easy solution, but we cannot see it. 

Greetings
Felix Hetterich

**Comment by qzminski** [comment]
Should be fixed in 3.0.14 which has been just released.
