### ISSUE TITLE
Server Error when a user has no limitation in news category roots

### ISSUE THREAD

**Issue by Webstylerin** [codefog/contao-news_categories#157]
Contao: 4.4.35
codefog/contao-news_categories: 3.1.0

I have a user group that I will grant access to all news categories. These users are allowed to edit, create and delete categories.

In the user group settings the "news category roots" is empty. The tool tip says: "Here you can limit the news category roots the user has access to. Note that the subcategories will included automatically!" I did not set a limit because I don't want a limit.

But when the user tries to open the categories or wants to set a category for a news item a internal server error shows up:

> An exception occurred while executing 'SELECT DISTINCT `hideInList` FROM tl_news_category WHERE id IN()': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1

When I set a limit to every category, no error appears. But I want unlimited access. :)

Is this a bug or are my settings/is my understanding wrong?

![User groups › Edit group ID 1 - Contao Open Source CMS 2019-03-22 10-27-13](https://user-images.githubusercontent.com/3033160/54813244-6af43600-4c8d-11e9-8793-80f5d7f58a93.png)

**Comment by bibib** [comment]
Same problem here - 
Contao: 4.4.35
codefog/contao-news_categories: 3.1.0

In Contao 3.5.34 no news categories permissions are set at all, but the user can choose one or more categories without a problem. After the update to Contao 4.4 I get the same error when trying to choose a category.
In the admin account, no error shows up.

**Comment by minidriverch** [comment]
Same problem here -
Contao: 4.7.1
codefog/contao-news_categories: 3.1.0

**Comment by qzminski** [comment]
Sorry for the late reply, it is now fixed in 3.1.1.

**Comment by minidriverch** [comment]
great, thank you
