### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rburch** [codefog/contao-news_categories#165]
It works, but {{news_categories::description}} isn't in your documentation yet.

**Comment by qzminski** [comment]
[The first paragraph in the docs](https://github.com/codefog/contao-news_categories/blob/master/docs/insert-tags.md#insert-tags) indicates that there are multiple insert tokens. I am not planning to create a complete list of the available tokens as it would be difficult to maintain. You can always preview the list of available fields e.g. in the language files: https://github.com/codefog/contao-news_categories/blob/master/src/Resources/contao/languages/en/tl_news_category.php

**Comment by rburch** [comment]
Understood. Thanks.
