### ISSUE TITLE
Trail CSS class is missing in categories navigation

### ISSUE THREAD

**Issue by theDyingMountain** [codefog/contao-news_categories#167]
At the moment only an active class is placed in the template. I need a trail class to select the parent element of an active child element.

**Comment by qzminski** [comment]
The fix has been released in 3.1.7.

**Comment by theDyingMountain** [comment]
I got the following error after Update to 3.1.7 `[2020-01-07 16:33:21] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Codefog\\NewsCategoriesBundle\\NewsCategoriesManager::getTrailIds() must be an instance of Codefog\\NewsCategoriesBundle\\Model\\NewsCategoryModel, null given, called in /www/htdocs/w018ed9f/live/vendor/codefog/contao-news_categories/src/FrontendModule/NewsCategoriesModule.php on line 345 at /www/htdocs/w018ed9f/live/vendor/codefog/contao-news_categories/src/NewsCategoriesManager.php:141)"} []`

**Comment by qzminski** [comment]
Sorry, should be fixed in 3.1.8.
