### ISSUE TITLE
category URL parameter setting in Contao 4.9

### ISSUE THREAD

**Issue by rustykowski** [codefog/contao-news_categories#170]
This setting should appear in the root-page, but it does not. How can i adjust the parameter to something other than "category"?

**Comment by fritzmg** [comment]
> How can i adjust the parameter to something other than "category"?

You can't currently. The extension needs to apply the palette changes to the `rootfallback` palette as well.

**Comment by qzminski** [comment]
Hey @rustykowski the issue should be solved in 3.1.11.

**Comment by fritzmg** [comment]
Hm, I think these changes will fail in Contao <4.9, as no such palette exists.

**Comment by qzminski** [comment]
@fritzmg of course 🤦🏻‍♂️ 62f0300 should do now, can you confirm?

**Comment by fritzmg** [comment]
Don't have the time to actually test, but I approve of these changes :)

**Comment by rustykowski** [comment]
Thank you, @qzminski ! Its working fine now in Contao 4.9.

I just also refreshed the extension in Contao 4.4 and got Version 3.1.3 of contao-news_categories. So there is no problem ;-)
