### ISSUE TITLE
Multiples Löschen erzeugt weiße Seite

### ISSUE THREAD

**Issue by chriza** [codefog/contao-news_categories#171]
Hallo,

werden mit "Mehrere Bearbeiten" 13 und mehr Nachrichten ausgewählt, wird beim Löschen eine weiße Seite erzeugt.

**Comment by qzminski** [comment]
Unfortunately I do not speak German. Can you describe the problem in English?

**Comment by planepix** [comment]
i can help too.
When choose ”edit multiple” with thirdteen or more messages, you get a blank page when deleting the selected items”

**Comment by qzminski** [comment]
Please check error logs in the `/var/logs/` folder for anything relevant.

**Comment by chriza** [comment]
Hello,
i made a video: https://we.tl/t-jr8Hne0DLP

**Comment by qzminski** [comment]
Please check error logs in the `/var/logs/` folder for anything relevant.

**Comment by chriza** [comment]
Excuse me. I continued to test. The problem is not this extension.
