### ISSUE TITLE
Subcategories are invisible in cumulative filtermodule

### ISSUE THREAD

**Issue by kampfq** [codefog/contao-news_categories#173]
When using the cumulative filter all subcategories are invisible, only the items at the first level are visible.
the $item['subitems'] array is empty

**Comment by qzminski** [comment]
That 's how this module work, just like the description says: https://github.com/codefog/contao-news_categories/blob/master/docs/frontend-modules.md#news-categories-cumulative-filter

**Comment by alexgit2k** [comment]
@qzminski I do not see it in the description that it is only displaying the first category-level. I want to combine different choosen sub-catgeories like in https://demo.designsandcode.com/sfpro-movie-reviews/search/ so all sub-categories have to be be used for cumulative filtering, not only the first level categories.

**Comment by qzminski** [comment]
See #178.
