### ISSUE TITLE
After Update to 3.2.1 no filter visible

### ISSUE THREAD

**Issue by sfx12** [codefog/contao-news_categories#174]
I have Contao 4.93 and after the update i dont see the filtermodul in Frontend.. so something is wrong, database is updated and all caches deleted!

**Comment by qzminski** [comment]
Do you recall what version you updated it from? There were some changes related to filters in 3.1.0…3.2.0.

You can also go to the filter module settings and check the starting level field value, it should probably be zero.

**Comment by sfx12** [comment]
i updated from 3.1.0 to 3.2.0 where can i find the starting level field value !?

**Comment by qzminski** [comment]
Sorry, which module are we talking about – `News categories list` or `News categories cumulative filter` ?

**Comment by sfx12** [comment]
News categories cumulative filter

**Comment by qzminski** [comment]
It should work pretty much the same. Please take a screenshot of all your module settings so I can try to reproduce the problem.

**Comment by sfx12** [comment]
OMG, im Sorry.. pls close the issue.. after update the modul-template was changed wrong (i dont know why) i have chosed mod_newscategories_cumulative and know it works!!!!
