### ISSUE TITLE
Unable to add categories as editor

### ISSUE THREAD

**Issue by alexgit2k** [codefog/contao-news_categories#176]
At the permission-settings for the news-categories it is only possible to set the the permission "Administrate" (others have "Add" and "Delete"). But with this permission it is only possible to edit existing categories, it is not possible to add new categories.

**Comment by theDyingMountain** [comment]
Any news about this? Currently, it's impossible to use categories for editors. In my case, the editor needs the right to create categories.

**Comment by qzminski** [comment]
I am unable to reproduce the issue. My testing user group settings are the following:

<img width="715" alt="CleanShot 2023-08-28 at 16 41 20" src="https://github.com/codefog/contao-news_categories/assets/193483/58374566-9bac-4775-8a26-88bb5dc9dc44">

And I can freely add new categories. What are your settings? How does the news categories backend module look like? Is there a "new category" button?

**Comment by theDyingMountain** [comment]
Okay, I had a deeper look inside the problem. It only occurs if no category exists. Then no paste button is visible. If categories exist, it works. Can you reproduce that?

**Comment by qzminski** [comment]
That one I can reproduce 🙂 Please update to 3.4.28 or 3.5.7 and the problem should be gone.

**Comment by theDyingMountain** [comment]
thx for fixing
