### ISSUE TITLE
Contao 4.9.x: Multilingual management with DC Multilingual

### ISSUE THREAD

**Issue by jankout** [codefog/contao-news_categories#181]
Hello Kamil, 

is there a new way to use https://github.com/terminal42/contao-DC_Multilingual with Contao 4.9.x? In the Contao Manager, I cannot find the extension any more. I would like to use it in my project. [Otherwise, the section of this topic in your documentation is not current any more. ](https://github.com/codefog/contao-news_categories/blob/master/docs/multilingual-features.md#category-language-management)

**Comment by fritzmg** [comment]
See https://github.com/contao/package-metadata/pull/129

Some packages are marked as a _dependency_ and thus are not discoverable as a Contao extension on extensions.contao.org or the Contao Manager.

**Comment by fritzmg** [comment]
However, you can still add suggested packages via the Contao Manager.

**Comment by asaage** [comment]
I have the same issue.
If you add it to composer.json the manager will install it.
It still works but for some reason it is missing in the search results.

**Comment by fritzmg** [comment]
See https://github.com/codefog/contao-news_categories/issues/181#issuecomment-714625462 ;)

**Comment by qzminski** [comment]
DC_Multilingual is maintained by terminal42 and as @fritzmg said, it is a marked as a dependency so it cannot be found through a regular package search. I think this is more an issue with Contao Manager itself rather than this extension.
