### ISSUE TITLE
Cumulative filter not showing categories

### ISSUE THREAD

**Issue by rburch** [codefog/contao-news_categories#182]
I'm having a hard time getting the cumulative filter to show. The regular category filter shows fine, but the cumulative filter is loading with nothing in it. Is it a bug or am I missing something

The html looks like this: 
`<div class="mod_newscategories_cumulative block"></div>`

Just a blank div. Any ideas why they wouldn't show?

Here's my configuration for the filter:
<img width="1170" alt="Screen Shot 2020-11-24 at 12 18 06 PM" src="https://user-images.githubusercontent.com/1537395/100129188-3c116880-2e4f-11eb-9bbc-94928c5cd174.png">

Here's the settings for my list module: 
<img width="1188" alt="Screen Shot 2020-11-24 at 12 20 32 PM" src="https://user-images.githubusercontent.com/1537395/100129370-7e3aaa00-2e4f-11eb-9d89-560624e60649.png">

**Comment by rburch** [comment]
Okay I sort of figured it out. The cumulative filter doesn't seem to show subcategories as I would expect. I have my categories 3 levels deep. I'm sort of treating it like you would navigation. The problem I'm facing is the root category needs to be selected and once it is it only shows one level deeper even though I have 2 levels deeper. I tried setting up multiple filters on one page but more than one seems to break the functionality. 

Here's a screenshot of how my categories are set up. I'd like that to be mirrored on the front end. Is there a way to do that?
<img width="1162" alt="Screen Shot 2020-11-24 at 3 00 43 PM" src="https://user-images.githubusercontent.com/1537395/100145221-0035cd80-2e66-11eb-82af-8487ef566000.png">

The other interesting thing is that you need to select the Parent category and the child category for it to show up. I think in most cases you logically you wouldn't need to select the parent because it's a giving that if it's. Child of the parent than the parent is a selection as well.

**Comment by rburch** [comment]
So after all that I see you recently released a new version that sounds like it is what I need. I tried to upgrade but get the following error in contao manager: 

$ /opt/cpanel/ea-php73/root/usr/bin/php -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=UTC /home/ampersand/public_html/web/contao-manager.phar.php composer update codefog/contao-news_categories contao/conflicts --with-dependencies --prefer-dist --no-dev --no-progress --no-suggest --no-ansi --no-interaction --optimize-autoloader
Dependency "contao/news-bundle" is also a root requirement, but is not explicitly allowed. Ignoring.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - codefog/contao-news_categories 3.4.1 conflicts with terminal42/dc_multilingual[2.1.7].
    - codefog/contao-news_categories 3.4.1 conflicts with terminal42/dc_multilingual[2.1.7].
    - codefog/contao-news_categories 3.4.1 conflicts with terminal42/dc_multilingual[2.1.7].
    - Installation request for codefog/contao-news_categories ^3.4.1 -> satisfiable by codefog/contao-news_categories[3.4.1].
    - Installation request for terminal42/dc_multilingual (locked at 2.1.7) -> satisfiable by terminal42/dc_multilingual[2.1.7].

**Comment by fritzmg** [comment]
You need to update all packages.

**Comment by rburch** [comment]
Yeah I did a few times. Everything upgrades but the news categories module. I'm running Contao 4.9.9 and the latest Isotope install which is where the dc_multiligual is coming from.

Here's my full plugin list:
      "asconsulting/contao_flexible_importer": "dev-master",
        "asconsulting/isotope_payment_stripe": "dev-master",
        "asconsulting/isotope_super_sort": "^1.0",
        "asconsulting/isotope_where_to_buy": "dev-master",
        "asconsulting/zyppy_class": "^2.0",
        "asconsulting/zyppy_popup": "^2.1",
        "codefog/contao-cookiebar": "^2.3",
        "codefog/contao-news_categories": "^3.3",
        "contao/calendar-bundle": "4.9.*",
        "contao/comments-bundle": "4.9.*",
        "contao/conflicts": "*@dev",
        "contao/faq-bundle": "4.9.*",
        "contao/listing-bundle": "4.9.*",
        "contao/manager-bundle": "4.9.*",
        "contao/news-bundle": "4.9.*",
        "contao/newsletter-bundle": "4.9.*",
        "dklemmt/contao_dk_mmenu": "^3.2",
        "isotope/isotope-core": "^2.6",
        "terminal42/contao-leads": "^1.4"

**Comment by rburch** [comment]
Okay, tried to just updated terminal42/dc_multilingual and ended up with this:

Problem 1
    - isotope/isotope-core 2.6.14 requires terminal42/dc_multilingual ~2.0 -> satisfiable by terminal42/dc_multilingual[2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7] but these conflict with your requirements or minimum-stability.
    - isotope/isotope-core 2.6.14 requires terminal42/dc_multilingual ~2.0 -> satisfiable by terminal42/dc_multilingual[2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7] but these conflict with your requirements or minimum-stability.
    - isotope/isotope-core 2.6.14 requires terminal42/dc_multilingual ~2.0 -> satisfiable by terminal42/dc_multilingual[2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7] but these conflict with your requirements or minimum-stability.
    - Installation request for isotope/isotope-core (locked at 2.6.14, required as ^2.6) -> satisfiable by isotope/isotope-core[2.6.14].
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
# Process terminated with exit code 2
# Result: Misuse of shell builtins

Seems like Isotope won't allow me to upgrade to the latest version of dc_multilingual which I think is 4.1.1. What's the best way to handle this? Is it a matter of changing restrictions in News Categories or is this a wait until Isotope updated to allow a newer version of dc_multilingual or is there another solution?

**Comment by qzminski** [comment]
You should be able to update all packages once Isotope reaches version 2.7 – https://github.com/isotope/core/milestone/88

**Comment by rburch** [comment]
Thanks, hopefully that is soon.

**Comment by qzminski** [comment]
I heard some gossips that it will happen still this year 🙄  I am closing this issue then.
