### ISSUE TITLE
translated categories disappear in the Frontend

### ISSUE THREAD

**Issue by asaage** [codefog/contao-news_categories#184]
setup:
contao: 4.10.5
news_categories: 3.4.1
DC_Multilingual: 4.1.1

I'm using a module "News categories list" with "Show empty categories" (but it happens in the comulative filters as well).
When i create a category it will show up in the list in the FE but as soon as i add one translation (en/de) to the Fallback the category is gone from the FE. Doesn't matter what the FE-language is.
As i can't really delete the translations thats even more a problem because i can't get my fallback-categories back.
Hope that is reproduceable.

**Comment by qzminski** [comment]
Would you be able to try the `dev-hotfix/3.4.2@dev` version on your system?

**Comment by asaage** [comment]
👍🏼 that works.

**Comment by qzminski** [comment]
Thanks, I have just released 3.4.2 stable so you can switch to that version :+1:
