### ISSUE TITLE
composer update with php 8.0 causes an error

### ISSUE THREAD

**Issue by grashalm4u** [codefog/contao-news_categories#192]
hello codefog,

due to the current changeover of my server to php 8.0, I wanted to call up "composer install" in the contao manager to load an alternative graphics library, as the "imagick" library required for php 8.0 is not yet available. therefore my site could not be opened after the change to php 8.0. after I called "composer install", it stopped with the message that I should call "composer update" first. After I did that, the composer update stopped again with the following message:

"Problem 1
    - codefog / contao-news_categories [3.1.0, ..., 3.4.5] require php ^ 5.6 | ^ 7.0 -> your php version (8.0.1.0) does not satisfy that requirement.
    - Root composer.json requires codefog / contao-news_categories ^ 3.1 -> satisfiable by codefog / contao-news_categories [3.1.0, ..., 3.4.5]. "

apparently your extension is not yet designed for php 8.0. can you adjust it soon, or would i have to wait several months? i ask because my hoster told me that i can count on the php 8.0 version of the "imagick" image library in about three to four months. then the error might have been resolved ...

greetings, grashalm

**Comment by fritzmg** [comment]
Do you need PHP 8?

**Comment by grashalm4u** [comment]
hello fritz,

no, I don't need it badly. i thought, if contao is already designed for it and it is available, i am updating my installation. but of course i can still work with php 7.4 for a while. this is not a problem.

**Comment by fritzmg** [comment]
> i thought, if contao is already designed for it and it is available

In theory yes, but new issues are still found. And since you won't have features like Imagick available in PHP 8 it probably does not make sense to use PHP 8 - unless there is a specific reason otherwise.

**Comment by grashalm4u** [comment]
Yes, thank you for your valuation. I think you are right: Very often it does make sense to wait for a while, until a new version is supported by additional software and can be installed without any further problems. I am no expert in these matters, so I am still learning a lot from all of you!
