### ISSUE TITLE
Contao 4.11 - Conflict (Hooks Class)

### ISSUE THREAD

**Issue by pressi** [codefog/contao-news_categories#194]
Hallo!

Contao Version 4.11.(5),  betrifft vielleicht auch andere.
Nach der Insallation ist das Frontend nicht mehr erreichbar.

Ich bekomme folgende Meldung im Log:
`"Attempted to call an undefined method named "parseCategoriesTags" of class "Contao\News"."`

In der **config.php** sollte bei den "parseArticles" und "replaceInsertTags" Hooks, "News" in "\NewsCategories\News" geändert werden.

```
$GLOBALS['TL_HOOKS']['parseArticles'][] = array('\NewsCategories\News', 'addCategoriesToTemplate');
$GLOBALS['TL_HOOKS']['replaceInsertTags'][] = array('\NewsCategories\News', 'parseCategoriesTags');
```

LG

**Comment by fritzmg** [comment]
If think you are using a very outdated version of this extension?

**Comment by pressi** [comment]
Oh, ja stimmt.
Hab gerade bemerkt wenn PHP 8 verwendet wird, wird automatisch eine alte Version installiert.
Version 2.8.10 hat die Abhängigkeit php >= 5.3.2 und die neueste Version 3.4.7 hat die Abhängigkeit php ^5.6|^7.0.

Es wird nicht möglich sein die aktuelleste Version unter PHP 8 zu installieren oder?

**Comment by fritzmg** [comment]
Only with `--ignore-platform-reqs`. You could then test the extension and report back whether the allowed PHP version can be increased without any further adjustments.

**Comment by pressi** [comment]
ok, danke.
Update auf die neueste Version hat ohne Probleme funktioniert.

Bis jetzt ist mir noch nichts aufgefallen.
Habe mal Kategorien erstellt, bei einer News zugewiesen und ein Modul für eine Kategorie-Liste erstellt. Hat alles funktioniert.

Verwende PHP Version 8.0.6.
Somit hat sich das Problem geklärt und das Bundle würde auch mit PHP 8.0 voraussichtlich funktionieren.

LG
