### ISSUE TITLE
tl_user.newscategories: data truncated

### ISSUE THREAD

**Issue by koertho** [codefog/contao-news_categories#205]
> String data, right truncated: 1406 Data too long for column 'newscategories' at row 1" at /usr/www/users/lftzky/live/anwaltverein.de/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 128 null []

I get this error for some users. The tl_user.newscategories field has only varchar 32, which seems to be very short for a serialized array. I think it should be blob or at least raised to 64 (I did last one to fix the error in my project).

Contao: 4.9.24
Bundle: 3.4.15
PHP: 7.4

**Comment by fritzmg** [comment]
As already mentioned on Slack, please post the complete stack trace. This field should never contain more than 24 characters, i.e.

```
a:1:{i:0;s:6:"manage";}
```
