### ISSUE TITLE
Compatibility with Contao 4.9.25

### ISSUE THREAD

**Issue by webworker-ecco** [codefog/contao-news_categories#207]
When saving a news item without selecting a category, the error message appears: 

Your selection contains invalid page IDs!

When saving a news with category/s set, the error message appears:

An exception occurred while executing 'UPDATE tl_news SET `categories`=NULL WHERE id='56'': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'categories' in 'field list'.

A similar error occurred with Rocksolid:

https://community.contao.org/de/showthread.php?82420-Update-auf-4-9-25-erzeugt-Problem-mit-Rocksolid-Elements

**Comment by fritzmg** [comment]
This is an error in Contao 4.9.25: https://github.com/contao/contao/pull/4067

**Comment by qzminski** [comment]
Thank you @fritzmg for clarifying this.
