### ISSUE TITLE
Error on creating/editing a News

### ISSUE THREAD

**Issue by freiwild** [codefog/contao-news_categories#208]
When creating or editing a news I get an error when saving the entry. With or without a selected news-category:

"An exception occurred while executing 'UPDATE tl_news SET `categories`=NULL WHERE id='50'': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'categories' in 'field list'"

There is no entry in the var/logs file.
I cleared the cache, updated all extensions, updated the database.
No change.

Before, i was able to assign categories to the news.

Contao 4.9.25, codefog/contao-news_categories 3.4.16, PHP 7.4

**Comment by fritzmg** [comment]
Duplicate of #207

**Comment by freiwild** [comment]
Thank you for that hint. Is there a solution or do i have to downgrade to 4.9.24?

**Comment by fritzmg** [comment]
Yes, you either need to downgrade or apply [this patch](https://github.com/contao/contao/pull/4067/files).

**Comment by freiwild** [comment]
Thanks! Will the patch be in the 4.9.26 included?

**Comment by fritzmg** [comment]
As it has already been merged: yes.

**Comment by qzminski** [comment]
Thank you @fritzmg for clarifying this!
