### ISSUE TITLE
Contao 4.13.2 Table 'tl_news_categories' doesn't exist

### ISSUE THREAD

**Issue by NewmansHub** [codefog/contao-news_categories#212]
Under 4.13 I get the error when saving a new news categories that the table tl_news_categories does not exist. If I understand it correctly here is correctly referred to the wrong database. In the meantime the table seems to be called tl_news_category.

https://github.com/codefog/contao-news_categories/blob/82b4b33bb69077d22448ed45f80b47992271ce19/src/Resources/contao/dca/tl_news.php#L52

The error unfortunately also leads to the fact that certain articles can no longer be restored because the function is accessed.

Is my assumption correct?

**Comment by qzminski** [comment]
Please open Contao Install Tool and see if there are any pending queries to execute.

**Comment by NewmansHub** [comment]
Hey,
thanks for the answer.

Of course we have done that several times. Also we have reinstalled and removed the plugin several times.

**Comment by qzminski** [comment]
The table `tl_news_category` stores the actual category data, whereas `tl_news_categories` is used as a relational table between `tl_news` and `tl_news_category`. The `tl_news_categories` table should be created automatically by the Haste extension and in the next "round" of the SQL queries after the `tl_news_category` has been created.

Have you got any other extensions installed on your system?
