### ISSUE TITLE
double rel=canonical tags

### ISSUE THREAD

**Issue by asaage** [codefog/contao-news_categories#217]
If you enable canonical urls for a news-category-list (opt_news_enableCanonicalUrls) and in the rootpage-setting(4.13) there is  rel-canonical already enabled (opt_enableCanonical) this results in two rel canonical tags on the page.
Just a minor issue because in this extension it's actually optional and only affects 4.13+ with mentioned root-page-setting.
For Isotope this was just fixed: https://github.com/isotope/core/issues/2310

**Comment by qzminski** [comment]
Please update to 3.4.21.
