### ISSUE TITLE
News Categories cannot be added or removed

### ISSUE THREAD

**Issue by eBlick-web-dev** [codefog/contao-news_categories#223]
The buttons pertaining the news category extension are all greyed out (disabled). We cannot select or remove categories in the individual news items. 

![image](https://user-images.githubusercontent.com/73280485/195606294-62965d57-a795-4352-b477-812f044defd0.png)

The categories themselves can still be edited.

I am not sure if this relates to the issue but in our logfile we get the following error when selecting to limit the categories: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `db123456`.`tl_news_archive`.`limitCategories` at row 1" at /...vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 117

**Comment by qzminski** [comment]
What is your Contao version?
