### ISSUE TITLE
Error with PHP 8.1

### ISSUE THREAD

**Issue by markaba** [codefog/contao-news_categories#229]
This error message occurs when trying to edit a news item (content element list):
`Symfony\Component\String\UnicodeString::__construct(): Argument #1 ($string) must be of type string, int given, called in /var/www/.../contao/vendor/codefog/contao-haste/src/DcaRelationsManager.php on line 619`

- using contao 4.13.15
- Running PHP 8.0 is not possible because of contao-haste requiring 8.1

**Comment by fritzmg** [comment]
This looks like an error in `codefog/contao-haste`, not `codefog/contao-news_categories`. You should report it there.

**Comment by markaba** [comment]
I will do this.... but it anyhow makes codefog/contao-news_categories unuseable...

**Comment by fritzmg** [comment]
> but it anyhow makes `codefog/contao-news_categories` unuseable...

You can downgrade to Haste 4 in the mean time.

**Comment by markaba** [comment]
do you please have a hint for me how I can achieve this? As `codefog/contao-haste ^5.0` is required by `codefog/contao-news_categories 3.5.0`...

**Comment by qzminski** [comment]
I will fix this in Haste package soon.

**Comment by qzminski** [comment]
@markaba could you please check if this commit solves the problem? https://github.com/codefog/contao-haste/commit/e32f31cfc4efc0653fa765963ffffedd3cb483c6

**Comment by markaba** [comment]
> @markaba could you please check if this commit solves the problem? [codefog/contao-haste@e32f31c](https://github.com/codefog/contao-haste/commit/e32f31cfc4efc0653fa765963ffffedd3cb483c6)

confirmed, [codefog/contao-haste@e32f31c](https://github.com/codefog/contao-haste/commit/e32f31cfc4efc0653fa765963ffffedd3cb483c6) solves the problem for me
@qzminski thank you

**Comment by qzminski** [comment]
Thanks, I have just released 5.0.13, so you can safely update the packages to a stable version.
