### ISSUE TITLE
Category aliases do not convert German umlauts

### ISSUE THREAD

**Issue by grashalm4u** [codefog/contao-news_categories#232]
Hello Kamill,

I've been using your "news categories" extension for a long time. Thank you for this great extension!

i noticed a bug: if the title of a news category contains a german umlaut, it is also generated in the alias and not replaced. this means that the settings under "valid alias characters" in the starting point of a website are not taken into account when generating aliases.
would be nice if you can fix that someday.

Greetings, grashalm

**Comment by fritzmg** [comment]
> this means that the settings under "valid alias characters" in the starting point of a website are not taken into account when generating aliases.

That's normal, since categories are not related to a specific page root. You have to use the **Valid alias characters** setting in the _System settings_ instead.

**Comment by grashalm4u** [comment]
hello fritz,

Thank you for this hint. I overlooked this setting. now everything is clear and the issue can be closed.

grashalm
