### ISSUE TITLE
Emty resetUrl when alias is "index"

### ISSUE THREAD

**Issue by keckmoritz** [codefog/contao-news_categories#237]
I have a News-Section with category filter on my home page. When i click on the filter, the link to reset the categories won’t appear if the alias of the page is "index" ($this->showTemplateVars() shows "resetUrl" => "").
It works as expected when the alias is something different ("resetUrl" => "startseite").

Link to the discussion in the contao forum: https://community.contao.org/de/showthread.php?84900-codefog-contao-news_categories-Kategorie-Filter-zur%C3%BCcksetzen-auf-Seite-quot-index-quot

**Comment by qzminski** [comment]
It should be fixed in 3.5.4 now.
