### ISSUE TITLE
Compatibility with Contao 5.x

### ISSUE THREAD

**Issue by jankout** [codefog/contao-news_categories#239]
Hello, 

is there any plan for new version for Contao 5.x? I would like to use it there too. Thank you.

**Comment by qzminski** [comment]
I will provide a support when Contao 5 LTS is out, unless there is somebody willing to sponsor this feature.

**Comment by aschempp** [comment]
see https://github.com/codefog/contao-news_categories/pull/241

**Comment by TS16V** [comment]
Contao 5.2.8

Problem in the frontend: 
https://community.contao.org/de/showthread.php?86226-Problem-Update-4-13-36-auf-5-1-11&p=579843&viewfull=1#post579843

What can i do?

**Comment by fritzmg** [comment]
@TS16V this extension has no stable release for Contao 5 yet.
