### ISSUE TITLE
Improve the newsListFetchItems Hook

### ISSUE THREAD

**Issue by derMatze82** [codefog/contao-news_categories#242]
If the [Contao Tags Bundle]( https://github.com/numero2/contao-tags) is used in parallel with this bundle, its newsListFetchItems hook no longer works.
This is because you always return a collection, even if no category filter is active.
Quick Fix:
`Codefog\NewsCategoriesBundle\EventListener\NewsListener`
```
public function onNewsListFetchItems(array $archives, $featured, $limit, $offset, ModuleNewsList $module)
{

    if (null === ($criteria = $this->getCriteria($archives, $featured, $module))) {
        return null;
    }

    $currentParam = $this->newsCategoriesManager->getParameterName();

    if (empty(Input::get($currentParam))) {
        return false;
    }
    ...
```

**Comment by fritzmg** [comment]
There can always only be _one_ `newsListFetchItems` hook.

An alternative solution is to use [`inspiredminds/contao-news-filter-event`](https://packagist.org/packages/inspiredminds/contao-news-filter-event). There exists a bridge for the `codefog/contao-news_categories` extension: [`inspiredminds/contao-categories-news-filter`](https://packagist.org/packages/inspiredminds/contao-categories-news-filter).

In order for this to work with the `numero2/contao-tags` extension you would either need to build your own bridge, or the `numero2/contao-tags` extension needs to switch from using the `newsListFetchItems` hook to the `NewsFilterEvent`.

**Comment by derMatze82** [comment]
Just to be sure, I don't want to filter by categories and tags at the same time, but either or.
The `numero2/contao-tags` extension would make that possible ;)
But thanks for pointing out the `codefog/contao-news_categories` extension!

**Comment by fritzmg** [comment]
I agree though that `NewsListener::onNewsListFetchItems` should return `false` if category filtering is not enabled at all for the respective news list module.
