### ISSUE TITLE
Search result only finds content on the 1st page 

### ISSUE THREAD

**Issue by netSpeedyTV** [codefog/contao-news_categories#244]
Problem with the search when setting the results to x per page. Search only find content on the 1st page. I don't know if it's because of the module, but if I set it up so that it doesn't split the news but all are on one page, it works.

**Comment by netSpeedyTV** [comment]
i have done this, after that search work but only for the 1 . Page, but if i use pagination it not find the other results on page 2. 3. xxx
<?php $this->extend('block_searchable'); ?>

**Comment by fritzmg** [comment]
In any case this has anything to do with this extension. You should seek help on the Contao Community Forum or Community Slack. For example, may be you enabled the Canonical Tag and did not add the query parameter for the pagination to the allowed query parameters.

**Comment by netSpeedyTV** [comment]
ok sry, but thx so i will look for that.
