### ISSUE TITLE
RSS Feed image media:content

### ISSUE THREAD

**Issue by rorych** [codefog/contao-news_categories#245]
A few years back contao changed the logic for adding images to the rss-feed:
https://github.com/contao/news-bundle/commit/050e8c330f86cfbb9883c10df7627a0f62734ad3

The "media:content" has been used since, instead of "enclosure".
In your override of the method generateFiles you still use the old call:
https://github.com/codefog/contao-news_categories/blob/master/src/FeedGenerator.php#L191

We noticed that on save_callback of news your method is used, but if you generate XML files via maintenance in the contao backend, the original method is used.
Leading to different xml structures each time someone saves a news or the xml is generated via daily cron.

Could you also use the new call with "media:content" parameter please?

`$objItem->addEnclosure($objFile->path, $strLink, 'media:content', $arrFeed['imgSize']);`

**Comment by fritzmg** [comment]
Is this still an issue with version 4 under Contao 5?

**Comment by aschempp** [comment]
Fixed in d0354961dfe4de69bd6cc812ca5a58483ae50efd

> Is this still an issue with version 4 under Contao 5?

it is not, because Contao 5 uses the new feed page where we can extend the core instead of replace everything.
