### ISSUE TITLE
Field tl_news.categories is not related! 

### ISSUE THREAD

**Issue by PAtrick1447** [codefog/contao-news_categories#251]
Hallo I installed  the Extension, but sadly it does not work, I always get the error "Field tl_news.categories is not related!".
Also I noticed that during the Installation the relationtable  "tl_news_categories" was not created.

Sadly i dont have any clue on  how to start from here, so i hope that someone could help me here.

![image](https://github.com/codefog/contao-news_categories/assets/129731700/3cef846a-aacf-4930-a627-4b3162ad3a31)
![image](https://github.com/codefog/contao-news_categories/assets/129731700/dab89ee8-2284-41f8-926f-71b1b68a7869)

**Comment by fritzmg** [comment]
Please create issues in English.

**Comment by digitalraumtcc** [comment]
We also installed it on a new contao and it worked like a charm. 
We only have this Problem with a Contao 4.13.30 that we have updated from 4.4. 

There is no Suggestion from the installtool to create the table, with the empty, new installed contao there is the Suggestion in the installtool.
