### ISSUE TITLE
Editor user role problem

### ISSUE THREAD

**Issue by DaxCheller** [codefog/contao-news_categories#252]
Contao 4.9.42
Contao News Categories 3.4.29

As an Editor I'm not able to edit or select some news categorys. Roles are set correctly.
As an Admin its all possible but when it comes to user roles I'm getting this error message: 

`Attempted to load class "ArrayParameterType" from namespace "Doctrine\DBAL". Did you forget a "use" statement for another namespace?`

Any suggestions?

**Comment by fritzmg** [comment]
Will be fixed by https://github.com/codefog/contao-news_categories/pull/253

**Comment by qzminski** [comment]
Thank to @fritzmg I have just released 3.4.30 stable which fixes this problem.
