### ISSUE TITLE
Compatibility with Contao 4.9

### ISSUE THREAD

**Issue by iosis101** [codefog/contao-news_categories#254]
Is this expansion not at all compatible with 4.9? 
I get this error in the news editing section: 
`An exception occurred while executing 'UPDATE tl_news SET `categories`=NULL WHERE id='1224'': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'categories' in 'field list'`

The column categories is indeed not existent (anymore?) in the tl_news table. 

I unfortunatly can't update to 4.13 because of other expansions...

Thanks in advance.

**Comment by amenk** [comment]
@iosis101 Did `vendor/bin/contao-console contao:migrate` run through without errors?

**Comment by fritzmg** [comment]
> Is this expansion not at all compatible with 4.9?
> I get this error in the news editing section:

Looks like you did not update your database.
