### ISSUE TITLE
5.3.0  Cannot open filter category + one more error

### ISSUE THREAD

**Issue by grashalm4u** [codefog/contao-news_categories#256]
Hello Kamill,

I've been using your extension contao-news_categories for a long time and I'm very happy that it exists. Thank you for that!
Recently I've been using Contao 5.3.0, your extension in version 4.0.3 with PHP 8.2.13. I noticed the following things (errors?):

1) When I select a filter category in the frontend, I get the following error code in debug mode:

vendor/codefog/contao-news_categories/src/FrontendModule/NewsModule.php:235
My site then also displays an error page in the frontend.

2) The template nav_newscategories inserts numerous spaces in front of the respective category in the string that "href" creates.

You can see error 1 if you go to my site:
[https://die-schreibmaus.de/meine-texte.html](https://die-schreibmaus.de/meine-texte.html)
click on one of the two green filter buttons and then make a selection in the pull-down menu.

It would be great if you could take a look soon.

The schreibmaus Lothar sends you kind regards

**Comment by fritzmg** [comment]
You did not post the actual error ;)
Also use the debug mode and post the complete stack trace.

**Comment by aschempp** [comment]
The error should be fixed in 4395d82476e156542f03fd4a8338cbacce48fb26 (version 4.0.4).

I don't understand the href problem, but please create a separate issue for that with more explanation if it still exists.

**Comment by grashalm4u** [comment]
Hi Andreas,

thanks for the quick revision! I can now select one or more filters and the active filters are listed, but selecting the filter categories has no effect on the display of news titles. Either all news titles are displayed, or none at all.

I also tested the whole thing again in a clean installation, but the list of news titles displayed always remains the same, regardless of which filters are activated. Is this still a bug in the current version 4.0.4, or am I doing something wrong?

Unfortunately I don't get any error message at all.

By the way, the incorrect display with several spaces in the generated link no longer appears since I installed version 4.0.4. This makes mistake number 2 from my last post unnecessary...

**Comment by aschempp** [comment]
You're welcome. Unfortunately, I was able to spot the code error by just reading the code. But I don't have a setup to reproduce the new error. If you could investigate that in the code (or have someone do that for you), we would be happy if you find the bug.

**Comment by grashalm4u** [comment]
Where exactly do I have to look? In the code of the template in question?
