### ISSUE TITLE
Reader-Page 404 + Server-Error 500

### ISSUE THREAD

**Issue by birdsinthesun** [codefog/contao-news_categories#259]
Hi,
i have this settings in the list-module:
![grafik](https://github.com/codefog/contao-news_categories/assets/73081731/fca8cc6b-031b-4208-a510-36f69885be1f)

and this settings in the reader-modul:
![grafik](https://github.com/codefog/contao-news_categories/assets/73081731/1d53183e-f987-4a20-bc6a-f0597cd312cf)

I have an error in the frontend, on the readers page:
![grafik](https://github.com/codefog/contao-news_categories/assets/73081731/cb9b5a19-8adb-49b5-8602-c3424a136943)

In the Logs is shown a deprecaded method
![grafik](https://github.com/codefog/contao-news_categories/assets/73081731/6deb1b4f-b2a5-4a76-accd-d0558c2ef713)

**Comment by fritzmg** [comment]
I don't think this has anything to do with this extension? Or why did you create this issue here? In any case, you should probably seek help in the Contao Community for these kinds of (likely misconfiguration) issues.

**Comment by birdsinthesun** [comment]
Why misskonfuration. I tryed different konfiguration. This extensio don't work, Sorry

**Comment by birdsinthesun** [comment]
solved the problem
