### ISSUE TITLE
I read the docs but there is no help

### ISSUE THREAD

**Issue by birdsinthesun** [codefog/contao-news_categories#260]
If I understand this extension the right way. I have to add a filter-modul to a page and a list-modul. If the configuration is ok, then the list will be filtered -right? Or have I have to change templates? I work with a Contao 5.3 Installation. I tryed all settings, but the list-filter don't work. The list has the template news_short. I tryed to inspect with 
´´´
  var_dump($_GET,$this->categories[8]['alias']);  
´´´. The Get-variable is ok, the categories are also ok (look at the screenshot)
![grafik](https://github.com/codefog/contao-news_categories/assets/73081731/9d67bf73-9db3-44be-a50f-3366f5909ae2)

please can you give me some advice?

**Comment by aschempp** [comment]
Please reach out to the Contao community (forums or Slack, see https://to.contao.org/support). I'm sure there are plenty of people with experience with this extension. The GitHub channel is for bug and feature tracking.
