### ISSUE TITLE
5.3: Filters don't work

### ISSUE THREAD

**Issue by grashalm4u** [codefog/contao-news_categories#261]
Hi Andreas,

I'm opening a new ticket again because I find the error in the news_categories essential. As I said, I can select filters, but they do not filter and always show all news as a result, or the overall selection of all news in the list does not change when I select filters. Since I can't program myself and don't know anyone who could help me, I'm turning to you again.
You said you don't have a test environment to check or recreate the error.
Today I installed a Contao demo, only with the news categories as an extension. If you tell me how I can send you the data securely, I can give you the link to the test environment, as well as access to the backend and FTP access, which I have already created. Then you should be able to quickly find out what the problem is.

I'm looking forward to hearing from you and sending kind regards to Switzerland,
grashalm

**Comment by fritzmg** [comment]
Which version did you install?

**Comment by grashalm4u** [comment]
I installed 4.0.4. You said, it is broken, too? What can I do know?

**Comment by grashalm4u** [comment]
I just saw that there is a current version 4.0.5. The error seems to have been resolved. The filters are working again! Thank you to everyone who made this possible!
