### ISSUE TITLE
empty spaces before the category-alias in the URL

### ISSUE THREAD

**Issue by birdsinthesun** [codefog/contao-news_categories#262]
Hi. the generated URL has empty spaces. So the filter can't work.

![grafik](https://github.com/codefog/contao-news_categories/assets/73081731/f1965309-d17f-41a3-9163-66bae0214b05)

**Comment by aschempp** [comment]
Can you add a screenshot of your module configuration please?

**Comment by birdsinthesun** [comment]
## Layout
![grafik](https://github.com/codefog/contao-news_categories/assets/73081731/15290fff-9a5a-479a-8e77-773c7829e999)

## Filter
![grafik](https://github.com/codefog/contao-news_categories/assets/73081731/4b45f302-6729-4074-aa73-e023cf5c28f8)

## Archiv
![grafik](https://github.com/codefog/contao-news_categories/assets/73081731/c52cd969-d005-43c1-af2b-88a4265202d6)

**Comment by aschempp** [comment]
I was interested in the navigation template as well 😅

**Comment by birdsinthesun** [comment]
![Screenshot_20240227_152308_Chrome](https://github.com/codefog/contao-news_categories/assets/73081731/e48c2a39-78f4-41ca-87e1-5f5bd774a523)

I didn't change anything.

**Comment by aschempp** [comment]
You did customized the `nav_newscategories` template. Does the error appear if you remove/rename that template as well?

**Comment by birdsinthesun** [comment]
I only have a look on it. I didn't customized anything :-). I try  once again with removing it. wait a minute

**Comment by birdsinthesun** [comment]
The error exits also without the template

**Comment by birdsinthesun** [comment]
![grafik](https://github.com/codefog/contao-news_categories/assets/73081731/d11bee18-b647-4f7e-a553-f16949d14ac7)
I didn't install Change Language. Maybe is there a reason?

**Comment by birdsinthesun** [comment]
I found the Line where the Error goes =)
There is a  %25s at the end of the PageUrl instead of %s
![grafik](https://github.com/codefog/contao-news_categories/assets/73081731/bb7c3d32-3828-4484-a6f8-9e43a28cbf15)

**Comment by aschempp** [comment]
Should be fixed in 3ec06c4e72192a95e446cf9325a2c8563a43783d

**Comment by cscheibelhut** [comment]
This has to be fixed in `CumulativeHierarchicalFilterModule` also, see #289
