### ISSUE TITLE
2 Filter

### ISSUE THREAD

**Issue by Misco** [codefog/contao-news_categories#265]
<img width="340" alt="image" src="https://github.com/codefog/contao-news_categories/assets/284490/4ab563dd-b5b1-4eb2-9d0e-f334589ac903">

my final goal is to have the filter to work like this.
the user can select one "Handlungsfeld" and one "Jahr" kumulativ.
is it possible, i try so hard...

Thanks

**Comment by aschempp** [comment]
as far as I now, there is no limit on the categories the user can select, you cannot fors them to select one of each parent category. You can only train them (and hope they follow the guide 🙈 ).

**Comment by Misco** [comment]
`var ele = $('#pub .mod_newscategories_cumulativehierarchical');

ele.find('select').on('change', function(e){
	e.preventDefault();
	
function removeFirstHfId(href) {
  let match;
  const firstHfMatch = href.match(/hf-/g);
  if (firstHfMatch && firstHfMatch.length >= 2) {
    href = href.replace(/hf-[^_]+__/, '');
  }
  const firstIdMatch = href.match(/id-/g);
  if (firstIdMatch && firstIdMatch.length >= 2) {
    href = href.replace(/id-[^_]+__/, '');
  }
  return href;
}
	window.location = removeFirstHfId($(this).val());
});`

Dieser Javascript Code erreicht das gewünschte Verhalten.
