### ISSUE TITLE
Category Filter doesn't work in generateXmlFiles Hook on version 3.x

### ISSUE THREAD

**Issue by theDyingMountain** [codefog/contao-news_categories#267]
The check in [config.php ](https://github.com/codefog/contao-news_categories/blob/3.4.x/src/Resources/contao/config/config.php#L51) should be changed to:

`['Contao\News', 'generateFeeds']` instead of `['News', 'generateFeeds']`

than it works for me.

**Comment by aschempp** [comment]
Thanks for the report! Fixed in cf8912b070a3d2f360c3c4cf3031a26403f293df
