### ISSUE TITLE
5.4: Fatal error in Contao Manager

### ISSUE THREAD

**Issue by jankout** [codefog/contao-news_categories#269]
Hello, if I try to upgrade to Contao 5.4 your extension ocurres an error in the Contao Manager. Could you check it and fix it,  please? Thank you very much. 

Best wishes. 

___________

Here is the error message. 

> Fatal error: Declaration of Codefog\NewsCategoriesBundle\Security\Voter\BackendAccessVoter::vote(Symfony\Component\Security\Core\Authentication\Token\TokenInterface $token, mixed $subject, array $attributes) must be compatible with Symfony\Component\Security\Core\Authorization\Voter\VoterInterface::vote(Symfony\Component\Security\Core\Authentication\Token\TokenInterface $token, mixed $subject, array $attributes): int in /www/htdocs/w01db1bd/ghetto-theresienstadt/contao/vendor/codefog/contao-news_categories/src/Security/Voter/BackendAccessVoter.php on line 51
> 129 packages you are using are looking for funding.
> Use the `composer fund` command to find out more!
> > @php vendor/bin/contao-setup
> PHP Fatal error:  Declaration of Codefog\NewsCategoriesBundle\Security\Voter\BackendAccessVoter::vote(Symfony\Component\Security\Core\Authentication\Token\TokenInterface $token, mixed $subject, array $attributes) must be compatible with Symfony\Component\Security\Core\Authorization\Voter\VoterInterface::vote(Symfony\Component\Security\Core\Authentication\Token\TokenInterface $token, mixed $subject, array $attributes): int in /www/htdocs/w01db1bd/ghetto-theresienstadt/contao/vendor/codefog/contao-news_categories/src/Security/Voter/BackendAccessVoter.php on line 51
> Script @php vendor/bin/contao-setup handling the post-install-cmd event returned with error code 255

**Comment by aschempp** [comment]
Should be fixed in c7ab3a6a1e8403f42b467ad4c25f2b791da81595
