### ISSUE TITLE
4.13.*: Defining reference page (Root) results in categories not being rendered

### ISSUE THREAD

**Issue by magic-77** [codefog/contao-news_categories#270]
I would like to define a category reference on a page. I have activated the “Reference category (root)” option and selected a category. But then the categories are no longer rendered.
My goal is to have a specific category automatically preselected when this page is called up,

This module is integrated on a page with the news list module
sorry, it is in german
![Bildschirmfoto vom 2024-08-29 21-32-22](https://github.com/user-attachments/assets/92574f1b-8a6a-40b9-8966-112fc7d92649)

**Comment by fritzmg** [comment]
You need to post your category tree.

**Comment by magic-77** [comment]
![Bildschirmfoto vom 2024-08-30 13-15-54](https://github.com/user-attachments/assets/71b64d77-c26d-4134-92c1-f8255c5ce0f9)

and here i included the modules
![Bildschirmfoto vom 2024-08-30 13-16-17](https://github.com/user-attachments/assets/76418ee4-5032-4c1c-91c7-ba512b149a52)

**Comment by magic-77** [comment]
@fritzmg 
yo mean this?
![Bildschirmfoto vom 2024-08-30 13-33-54](https://github.com/user-attachments/assets/519f372e-b36b-44e7-a7e1-f97b002d2394)

**Comment by fritzmg** [comment]
Yes. You have set the reference page to "Alle". This is why you are not seeing any categories, as "Alle" has no sub categories.

**Comment by magic-77** [comment]
ok, got it, thank you! But how it is possible to redirect to a specific category per default when entering the url?

**Comment by fritzmg** [comment]
I am not sure what you mean. For general questions you can also use the Contao Community Forum and Contao Community Slack.

**Comment by magic-77** [comment]
when i enter the blog url i get the categories like this, but none is selected per default
![Bildschirmfoto vom 2024-08-30 14-07-01](https://github.com/user-attachments/assets/2ec5e6c1-a14b-4763-b66b-d7610c6c2a06)

but i would like to define the "Alle" category when entering the blog url as default to get this
![Bildschirmfoto vom 2024-08-30 14-07-13](https://github.com/user-attachments/assets/992fc803-1d5c-427c-b6e2-4d1c407f9520)

i tried already to ask at contao community without success, therefor i try to get help here

**Comment by fritzmg** [comment]
This is for bug reports only.

**Comment by magic-77** [comment]
ok, last question, is this even possible what i try to reach?
