### ISSUE TITLE
TreePicker not working on Win browsers

### ISSUE THREAD

**Issue by rocchidavide** [codefog/contao-news_categories#54]
TreePicker seems that's not working on Firefox and Chrome on Windows browsers (IE works): I can check categories but click on 'Apply' does nothing. Console outputs this error:

Error: Permission Denied to access property 'name' (treepicker.js line 110)

content.js:4 Iframe attached successfully
app.js:3 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
2treepicker.js:110 Uncaught SecurityError: Blocked a frame with origin "http://(MYSITE)" from accessing a frame with origin "chrome-extension://flliilndjeohchalpbbcdekjklbdgfkk".  The frame requesting access has a protocol of "http", the frame being accessed has a protocol of "chrome-extension". Protocols must match.

**Comment by qzminski** [comment]
Can you check if other Contao popups work for you?

**Comment by rocchidavide** [comment]
Ok, I checked and the problem was the Avira antivirus plugin: deactivating it in every browser, the problem is solved. Sorry!
