### ISSUE TITLE
Issue with namespace

### ISSUE THREAD

**Issue by fritzmg** [codefog/contao-news_categories#55]
In general, all the Modules etc. are within the namespace `NewsCategories`. However, in some places, these classes are not referenced with the namespace. For instance the front end module and content element is referenced in the `config.php` without the preceding namespace `NewsCategories\…`.

Also there may be a specific problem in [ModuleNewsCategories.php#L76](https://github.com/codefog/contao-news_categories/blob/master/modules/ModuleNewsCategories.php#L76).
```php
$strClass = \NewsCategories\NewsCategories::getModelClass();
$objCategories = $strClass::findPublishedByParent($this->news_archives, ($this->news_customCategories ? deserialize($this->news_categories) : null));
```
`\NewsCategories\NewsCategories::getModelClass()` actually returns `\NewsCategoryModel` - this would translate to the default Contao Namespace, but there is no `NewsCategoryModel` within the Contao namespace of course.

Weirdly, I cannot confirm all this on my local webserver, but someone in the Contao Forum has this Problem: https://community.contao.org/de/showthread.php?43215-Nachrichtenliste-nach-Kategorien-filtern&p=365976&viewfull=1#post365976

**Comment by qzminski** [comment]
As far as I know the ```\NewsCategories``` translates to the global namespace and not to the ```Contao``` namespace? Can you try to update the below line to contain correct namespace and check if it works?

https://github.com/codefog/contao-news_categories/blob/master/classes/NewsCategories.php#L100

**Comment by fritzmg** [comment]
True, it translates to the global namespace and Contao's class loader actually maps classes to the global namespace, so it should be available under `\NewsCategoryModel` without the preceding `NewsCategories` namespace.

**Comment by qzminski** [comment]
Try to update this line

https://github.com/codefog/contao-news_categories/blob/master/classes/NewsCategories.php#L100

to

```php
return static::checkMultilingual() ? '\NewsCategories\NewsCategoryMultilingualModel' : '\NewsCategories\NewsCategoryModel';
```

**Comment by fritzmg** [comment]
I know, the problem is I can't reproduce it on my system :). And everything should work as expected. I have asked xkoy on the forum for his PHP version, may be it's insufficient for Contao's mapping of classes to the global namespace.

**Comment by Dani79** [comment]
Hi,

i have the problem :)

You can see the error msg live here:
(I have updated the line 100, bute the same error)

http://www.magdalena.at/de/hotel-neuigkeiten-magdalena-zillertal.html

**Comment by Dani79** [comment]
ok, here my error from my test page:
Fatal error: Class '\NewsCategoryModel' not found in /var/www/vhosts/pixelgenau.at/testumgebung.pixelgenau.at/system/modules/news_categories/modules/ModuleNewsCategories.php on line 76

And here with the line 100 "fix"

Fatal error: Class '\NewsCategories\NewsCategoryModel' not found in /var/www/vhosts/pixelgenau.at/testumgebung.pixelgenau.at/system/modules/news_categories/modules/ModuleNewsCategories.php on line 76

**Comment by qzminski** [comment]
@Dani79 is it the newest Contao version?

**Comment by Dani79** [comment]
Hi,

its 3.2.20.

**Comment by qzminski** [comment]
Hmm, do you have some other extensions installed? I actually have no clue what could be wrong as it is the first such issue with this module.
