### ISSUE TITLE
Limit the manage news categories by user group / user

### ISSUE THREAD

**Issue by fatcrobat** [codefog/contao-news_categories#56]
Hi there, 

thanks for this module. Is it possible to add an limitation to manage news categories by user group / user permissions?

If you like, i can create a pull request.

**Comment by qzminski** [comment]
It is already possible for user and the user groups:

https://github.com/codefog/contao-news_categories/blob/master/dca/tl_user.php#L24

**Comment by fatcrobat** [comment]
Already tried, but always shows the top level for the limited user.

**Comment by qzminski** [comment]
Would you like to set the permissions for each category individually? That's not yet implemented so PR is very welcome :smile:

**Comment by fatcrobat** [comment]
I think so.




Need the following Szenario. 




User Group A - News Category Root A


User Group B- News Category Root B





______________________________

Rico Kaltofen
Hartigstrasse 8
01127 Dresden
E-Mail: Rico.Kaltofen@gmail.com
Mobil: 0172/352 90 20

**Comment by qzminski** [comment]
Yup, then you need to create a pull request.

**Comment by fatcrobat** [comment]
Alright, do my best to implement this next days.

**Comment by nafetagrats** [comment]
I have taken on this task and created a PR

**Comment by qzminski** [comment]
Implemented in bb8d6e3.
