### ISSUE TITLE
Feature request: The category list direct included on the first level of a news

### ISSUE THREAD

**Issue by jenda77** [codefog/contao-news_categories#59]
I would finde better when the category list could be direct included into the first level of a news - like by this extension http://www.martin-eberhardt.com/mae_event_categories.html

I think it could be more user-friendly. What do you think? 

Best wishes, Jan

**Comment by qzminski** [comment]
What do you actually mean? How is this approach different?

**Comment by jenda77** [comment]
See the screen shots on his website. I think it could be better to have the categories list directly there not first after a click. What do you think?

**Comment by qzminski** [comment]
From what I see in this picture it's the same as news categories.

![](http://www.martin-eberhardt.com/files/content/eventCat/cat1.jpg)

**Comment by jenda77** [comment]
I mean when you edit a news on the first level (not the archive). :-)

**Comment by qzminski** [comment]
You mean the global operation button here?

![zrzut ekranu 2015-06-08 o 20 24 29](https://cloud.githubusercontent.com/assets/193483/8041990/65705a82-0e1c-11e5-91c2-0d72952944b1.png)

**Comment by jenda77** [comment]
See the picture in my post before.

**Comment by qzminski** [comment]
I still have no idea what you mean. The news settings looks like this currently:

![zrzut ekranu 2015-06-08 o 21 50 20](https://cloud.githubusercontent.com/assets/193483/8043763/6f89b980-0e28-11e5-86a4-0e593b4f38bf.png)

**Comment by jenda77** [comment]
yes, you have to click on the button first to be able to add it. The other solution works without the button. This is what I find better. ;-)

**Comment by qzminski** [comment]
How would you solve the category nesting problem?

**Comment by jenda77** [comment]
Ok, this is the anti-argument. ;-) you are right. ;-)
