### ISSUE TITLE
Apply button does not work - news archive

### ISSUE THREAD

**Issue by jenda77** [codefog/contao-news_categories#60]
Hello, 

unfortunately, the apply button does not work when I am trying to choose the categories for a news archive (Contao 3.5, your extension 2.6.0). The close button works fine there. 

I have tried in another content elements like picture element and there it works well. Maybe, something is not there for the javascript function? 

Best wishes, Jan
![bildschirmfoto 2015-06-11 um 12 25 04](https://cloud.githubusercontent.com/assets/3715050/8104994/5cdffeca-1035-11e5-942d-4e3c2903fea4.png)

**Comment by qzminski** [comment]
Have you updated the widget_tree_picker extension to 2.0.1?

**Comment by jenda77** [comment]
Yes, this is also up to date.

Now I have figured out that this does not work by a news too when I want to choose a news category.

**Comment by qzminski** [comment]
Please try to refresh your JavaScript cache. If that still does not work, try opening the JS console and check if there are any errors.

**Comment by jenda77** [comment]
Ok, it works again. Thank you for your quick help. I did not know it.
