### ISSUE TITLE
Contao 3.5 contao-legacy/news_categories

### ISSUE THREAD

**Issue by chriza** [codefog/contao-news_categories#62]
Hi,
i use contao-legacy/news_categories in a Contao 3.5 installation.

My problem: the "apply" button doesn't work.

What is my mistake?

Best wishes

**Comment by qzminski** [comment]
You should update the news_categories to 2.6.0+ and widget_tree_picker to 2.0.1+

**Comment by chriza** [comment]
Hi,
i tried in two C 3.5 installations to install the 2.6.1 version.
It is not possible. See picture.
![news-categories](https://cloud.githubusercontent.com/assets/1572887/8591222/0ed6f91a-2627-11e5-84e7-0874406d9249.jpg)

**Comment by qzminski** [comment]
Have you tried installing the extension directly from my vendor instead of contao-legacy?

https://packagist.org/packages/codefog/contao-news_categories

**Comment by chriza** [comment]
Hi,

now i have contao-leagy deinstalled an tried to install codefog/contao-news_categories.
I cannot install this version. (PH-Version: 5.5)
![2015-07-09_13-31-43](https://cloud.githubusercontent.com/assets/1572887/8594238/64a7f7fa-263f-11e5-8267-0f30706db73e.jpg)

**Comment by qzminski** [comment]
Are you sure you are using Contao 3.5? I see you cannot install 2.6 but you can install 2.5.

**Comment by chriza** [comment]
yes. Originally, this installation was Contao 3.4.5.
My packets-list:
![contao-3-5-0-packets-list](https://cloud.githubusercontent.com/assets/1572887/8596513/26842712-2650-11e5-80f8-53b1af829796.jpg)

**Comment by qzminski** [comment]
I think there is something wrong with your installation. The composer data for the extension is correct.

https://packagist.org/packages/codefog/contao-news_categories

**Comment by chriza** [comment]
Now I have a fresh Contao 3.5 installation on my shared hosting packet.
Same problems. (Apache modul: PHP 5.4)
![news-categories-1](https://cloud.githubusercontent.com/assets/1572887/8618102/2371eb16-270b-11e5-84bf-ec6eb88a1a5d.jpg)
![news-categories-2](https://cloud.githubusercontent.com/assets/1572887/8618103/25ab6f56-270b-11e5-8d7d-a9862e35f4d8.jpg)

**Comment by qzminski** [comment]
I have installed the Contao locally and have the same situation as you do but I have no idea where the problem lies. Please try to force-install the 2.6.1 - just click the "mark package to install" and update the packages.
