### ISSUE TITLE
Show class on category menu item also when one of its news items is viewed

### ISSUE THREAD

**Issue by fritzmg** [codefog/contao-news_categories#64]
It would be nice if the category menu also has an `active` or `trail` class (or something to that effect) if the news item that you are currently viewing on your news reader is a member of that category.

e.g. ModuleNewsCategory could check for something like
```php
$arrCategories = array();
if( ( $objNews = \NewsModel::findByAlias( \Input::get('auto_item') ) ) !== null )
{
	$arrCategories = deserialize( $objNews->categories );
	$arrCategories = $arrCategories?: array();
}

…

$strClass.= in_array( $objCategories->id, $arrCategories )? ' trail' : '';
```
(simplified)

**Comment by qzminski** [comment]
What if the news is assigned to multiple categories? Should they be all listed as active in the menu?

**Comment by fritzmg** [comment]
Well actually `trail`, would be better since that would mimic the behaviour of the regular navigation module and treat a news entry as a subpage of a category. 

And yes, if a news entry is assigned to several categories, then all of those would get the class (if they are visible in the category navigation in the first place).

**Comment by qzminski** [comment]
Implemented in b93ab4c.

**Comment by fritzmg** [comment]
Hm, I would actually prefer the `trail` class over `news_trail`, because then it is more convenient to apply the same styling to a news category menu as to a navigation menu ;)

**Comment by qzminski** [comment]
The current implementation allows you to distinguish those two different cases if needed and still gives you the possibility to style them the same. Obviously having only one ```trail``` class could be problematic for the users that want to style those items separately.
