### ISSUE TITLE
Category Name as Headline above a category-filtered Newslist

### ISSUE THREAD

**Issue by b-fender** [codefog/contao-news_categories#66]
Dear qzminski,

first of all thank you for your very practicable extension!

Whren i worked with your extension i found out, that it would be a nice feature to have access to
a variable with the "active category name" to use it as a Headline ABOVE a category-filtered
list of news-items. (and it changed, when you clicked on another category)

But this is maybe not so easy, i think therefore the variable of the "active category name"
had to be present also in the template "mod_newslist", which i think is not the case.

What do You think: Would that be an option for you to implement in your extension? 

So far I helped myself with a bit Javascript to read the text of the active category and 
injected that into a common Headline which resides above the newslist. 
But this is a not very nice way.

I hope, i could describe more or less clearly what i mean and would be happy to hear from you ;-)

The very Best Regards: Joc

**Comment by qzminski** [comment]
Implemented in 14b34f0. From now on you can use the ```{{news_categories::*}}``` insert tag which will print information about the current category. Examples:

```{{news_categories::title}}``` prints category title
```{{news_categories::frontendTitle}}``` prints category frontend title
