### ISSUE TITLE
add auto_item feature

### ISSUE THREAD

**Issue by matzke** [codefog/contao-news_categories#71]
it would be nice, if i could use auto_item ... eg /news/category/X.html would become news/X.html

**Comment by qzminski** [comment]
Won't it collide with other modules, e.g. news reader page?

**Comment by fritzmg** [comment]
> Won't it collide with other modules, e.g. news reader page?

Well, that's the case with any module that uses the item or auto_item parameter.

**Comment by qzminski** [comment]
You are right but if there is a news reader module on the same page (either as a standalone module or connected with news archive module) then the auto_item feature will collide and cause either:

1. To make news archive module disappear and try to display news reader module
2. News reader module to mark page as unsearchable (regular behavior like if no news article is found)
3. News categories module not to mark the correct category as active

Thus I think we cannot implement it. Apart from the news_categories, I can't think of any situation where you place two modules that use auto_item feature on the same page.

Any counter arguments?

**Comment by fritzmg** [comment]
imho it should just be optional - and if enabled, it would be a natural limitation not to be able to place a news list (which might be filtered by the category from the `auto_item` parameter) and a news reader (which would show a news item from the `auto_item` parameter) on the same page.

**Comment by qzminski** [comment]
Where would you place that setting then? In the site structure just like an option to translate category parameter?

**Comment by fritzmg** [comment]
Hm, maybe in the system settings, since that's where you would also enable/disable the usage of the `auto_item` parameter.

**Comment by qzminski** [comment]
Honestly I think this "feature" will cause more harm than good and as this is quite an edge case I decide not to implement it for the time being. If there are more requests for this it can always be reconsidered.
