### ISSUE TITLE
Conflict with newslanguage

### ISSUE THREAD

**Issue by luger95** [codefog/contao-news_categories#74]
Hello,

Conflict with newslanguage https://github.com/terminal42/contao-newslanguage module.

Your module prevents newslanguage returned to the protected events, like another language.

Housed exchange languages, newslanguage and news_categoriesn create a news archive protected in both languages with two protected news and tried to pass from one to the other on the front.

THX

**Comment by qzminski** [comment]
Can you explain on a real world example perhaps? I did not quite get your issue description.
