### ISSUE TITLE
Frontend form with category single select

### ISSUE THREAD

**Issue by Hendriks** [codefog/contao-news_categories#80]
Hi there,

may I ask you for some advice here? Thank you in advance.

I'm having a frontend form for logged in members to post news, with a field of type "select menu (db)" feeded by tl_news_category and saving this (in this case) **single** select value to tl_news.categories. But as the concept of your extension is to handle multiple values, this field is expecting the value to be serialized (blob)...

As I'm not so experienced yet in customizing Contao modules, may I ask you, what do I have to do, to get this working?

Any suggestions?

Regards.

**Comment by qzminski** [comment]
Not only you have to save the serialized values but also update the relations table. I am afraid there is no 3rd party module that would cover your needs. The only way is to create a custom extension which requires some PHP and MySQL knowledge.

**Comment by Hendriks** [comment]
Ah, ok... I already suggested that the relations table has to come into play too...

Are you willing to build this (little) custom extension for me? I can pay you something for it. How much effort would it be for you? How much would you charge for this?

**Comment by qzminski** [comment]
Sorry, I am not available for the time being.

**Comment by Hendriks** [comment]
Ok. So I'll try to level-up my own skills meantime... ;) Thank you and maybe "hear" you again...
