### ISSUE TITLE
Bug: Assigning of news_categories to a news article wont work since contao 3.5.6

### ISSUE THREAD

**Issue by danielhoover** [codefog/contao-news_categories#83]
Dear qzminski,

I have a contao installation running Version 3.5.6 (update via Live Update). Since the Update the news_categories Module has a Bug. If I try to add news_categories to the news article a javaScript error is thrown and therefore the Overlay is not closed. I manually updated my news_categories to Version 2.7.0 but I've got the same issue.
I've added screenshots and hope this is of any help. I tried it in Chrome and Firefox. Both the same Problem - so obviously no webkit issue.
Any help would be kindly appreciated!

If you need any further information or more information on how to reproduce - feel free to ask for it.

Kind regards
Daniel

See Screenshots (unfortunately in german) below.

![screenwitherror](https://cloud.githubusercontent.com/assets/4067099/13662972/a07bd420-e69e-11e5-9e0a-3ed439969b02.png)
![errorwithinconsole](https://cloud.githubusercontent.com/assets/4067099/13662973/a07ce68a-e69e-11e5-874a-64e8f67596a0.png)

**Comment by fritzmg** [comment]
Have you deleted your browser cache?

**Comment by danielhoover** [comment]
Yes - I also reloaded the page with open Developer Tools which forces no caching. Also I cleared every cache in Contao.

**Comment by fritzmg** [comment]
Why did you manually update the Extension? You should use composer or the ER2. According to your screenshot you are still using old JavaScript code. Completely deinstall the extension, clear the composer cache if you use composer, make sure the folder in system/modules is gone and the reinstall it again.

**Comment by danielhoover** [comment]
Ahhhh. Thanks! Seems like I am totally stupid. I forgot to manually update the widget_tree_picker as well. Sorry! Now everything is solved!
