### ISSUE TITLE
change categories > apply not working - TypeError

### ISSUE THREAD

**Issue by danielroeding** [codefog/contao-news_categories#84]
Hi,
after update to contao 3.5.x i can´t change categories in some news. 
Click on "apply" button don´t work. 
When i downgrade to contao 3.4.5 it works.

Error log in google chrome console:
TypeError: h.document.getElementById(...) is null
TreePicker.openModal/<()
 treepicker.min.js:1
.addEvent/a()
 685053ef4baa.js:3

My modules versions:
widget_tree_picker 	2.2.0 build 3
news_categories 	2.7.0 build 3

**Comment by fritzmg** [comment]
Have tried deleting your browser cache?

**Comment by qzminski** [comment]
Please update your ```widget_tree_picker``` to the newest 2.3.0 version and as @fritzmg suggested make sure your browser cache is refreshed.

**Comment by danielroeding** [comment]
OK. After update ti 2.3 and cleaning the browser cache it works. 
thx :)
