### ISSUE TITLE
implement news feed fixes from Contao 3.5.9 and up

### ISSUE THREAD

**Issue by fritzmg** [codefog/contao-news_categories#86]
Since `news_categories` replaces the `Contao\News` class and brings its own `News::generateFiles` method, it should implement the fixes introduced in contao/core@354b3a4dfe7d3a341df7767f37b13fc299bad52b and contao/core@dcdf0c4ef97928fa98980225cccd7114199e9c6e . Otherwise the feed generation will be wrong in multidomain setups.

However, keep in mind that the method `PageModel::getAbsoluteUrl` is only available from Contao `3.5.9` and up. I can make a PR - but I'd rather bump up the Contao requirement to `>=3.5.9,<4-dev` than try to remain compatible with lower Contao versions.

**Comment by qzminski** [comment]
PR is very welcome. We can bump the Contao dependency to 3.5.9, that's not a problem.

**Comment by fritzmg** [comment]
PR created in #87

**Comment by qzminski** [comment]
PR merged and closed, thank you!
