### ISSUE TITLE
New feature:  display empty categories 

### ISSUE THREAD

**Issue by cob-web** [codefog/contao-news_categories#89]
In some cases it could be useful to display also empty categories in the categories list - also with a (0) behind. The benefit of this is, that the visitor can see there are more news categories but some of them have currently no news in it (for example in a vacancy board).
Thanks!!!

**Comment by fritzmg** [comment]
:+1: from me too, since I needed that in two projects already ;).

**Comment by qzminski** [comment]
Implemented in b55b14d.
