### ISSUE TITLE
Category alias is not generated without permissions

### ISSUE THREAD

**Issue by jacobro** [codefog/contao-news_categories#90]
Contao 3.2.21 news-categories 2.7.0
When BE user has no permission for field 'alias' and adds a new category, alias is not generated automatically. In FE this category is useless as it shows link with empty category (sth like /blog/.html).

I feel that 'alias' field is not necessary to be visible for editors (BE users, not superadministrators)

**Comment by qzminski** [comment]
That is also the case with the other Contao modules, like articles, news, events, etc. and I think it's perfectly fine. If you have no access to the field then it should not be saved, no matter if its value is auto-generated or not.

**Comment by fritzmg** [comment]
Indeed, this is a Contao issue. It lacks a built-in ability for such cases unfortunately.

**Comment by jacobro** [comment]
It does not matter if it is Contao or not Contao problem. The most important should be that categories become unusable when no alias is set. Maybe regenerateAlias should be executed when name changes and maybe it should check permissions. Alias field is crucial.

**Comment by fritzmg** [comment]
It does matter if it's a Contao problem. Contao's DCA system is designed this way. And as already mentioned, you would run into the same problem with news, page and article aliases for example. 

This is a feature request for Contao.

**Comment by fritzmg** [comment]
@jacobro see here for a solution to disable the alias field but keep its functionality: https://github.com/contao/core/issues/7957#issuecomment-128111939
