### ISSUE TITLE
No categories listed when creating/editing a new news item

### ISSUE THREAD

**Issue by nrunde** [codefog/contao-news_categories#96]
The news categories header is shown but there are no categories for selection listed.

![grafik](https://cloud.githubusercontent.com/assets/1148170/21010580/1c9939f0-bd4d-11e6-9b62-4b74dc991d14.png)

It's a fresh installation with only news_categories extension (and dependencies) installed via composer.
Contao version is 4.3.0

**Comment by qzminski** [comment]
Sounds like the [codefog/contao-widget_tree_picker](https://github.com/codefog/contao-widget_tree_picker) is not compatible with Contao 4.3. I will check that when I have a free minute.

**Comment by nrunde** [comment]
Seems so. Would be great if you find some free minutes to fix this issue, maybe between the years ;)

**Comment by qzminski** [comment]
Can you check if it works under Contao 4.3.1? I have that version installed + news_categories v2.7.5 + widget_tree_picker v2.3.2. It works just fine for me there:

![2017-01-09 at 11 22](https://cloud.githubusercontent.com/assets/193483/21763410/109a7b1c-d65e-11e6-9a0c-d2c8d2c15044.png)

**Comment by qzminski** [comment]
Also, is the cache rebuilt? Have you added both modules to AppKernel.php?

```php
new Contao\CoreBundle\HttpKernel\Bundle\ContaoModuleBundle('news_categories', $this->getRootDir()),
new Contao\CoreBundle\HttpKernel\Bundle\ContaoModuleBundle('widget_tree_picker', $this->getRootDir()),
```

**Comment by nrunde** [comment]
I'll try when I have some minutes

**Comment by nrunde** [comment]
Updated contao and all dependencies. Now it works as expected. Thank you
