### ISSUE TITLE
funktioniert nicht auf Contao 4.3.5

### ISSUE THREAD

**Issue by jedoStyle** [codefog/contao-news_categories#97]
leider funktioniert diese Erweiterung nicht mir Contao 4.3.5

wenn ich sie über Composer installieren sucht er im Verzeichnis "app" eine autoload.php, die es da nicht mehr gibt.

wenn ich es ins module Verzeichnis kopiere bekomme ich eine bei Auswahl der Kategorien in den NEWS eine 404 Meldung:

- Contao 4.3.5 Management Version
- News Categorie 2.8.0

**Comment by qzminski** [comment]
Can you please provide the English description of the issue?

**Comment by jedoStyle** [comment]
this extension doesn't work on Contao 4.3.5 management version

If I install it with composer the extension looks an autoload.php that no longer exist in the directory "app".

When I copy it into the modules directory I get a selection of categories in the NEWS a 404 message

**Comment by qzminski** [comment]
I think it's a problem related to #98. Let me keep that issue open and close this one.
