### ISSUE TITLE
[Contao 4] "Change selection" remain empty

### ISSUE THREAD

**Issue by netzarbeiter** [codefog/contao-news_categories#98]
- Contao 4.3.5 / Tested with PHP 5.6, 7.0, 7.1
- News categories (2.8.0)

Set up news categories, create a new item in the news archive and try to select a news category.

![news_categories](https://cloud.githubusercontent.com/assets/1942550/23104844/9ccda4f0-f6d5-11e6-8e19-3776a9aaafea.png)

**Error message:**
Failed to load resource: the server responded with a status of 500 (HTTP/2.0 500)
system/modules/widget_tree_picker/public/treepicker.php?do=news&table=tl_news_archive&field=categories&act=show&id=1&value=&rt=5jyFC4Vl6-QSwC8U150gq34iwtLFTPNFsRHTt0PBGRA

Same behaviour within Isotope: https://github.com/isotope/core/issues/1771

**Comment by qzminski** [comment]
See https://github.com/contao/manager-bundle/issues/19.
