### ISSUE TITLE
[Contao 4] Create file in the wrong directory

### ISSUE THREAD

**Issue by netzarbeiter** [codefog/contao-news_categories#99]
If you set up a RSS feed for the News the generated XML-File will be created in the directory **share** instead of **share/web**.

[news-bundle](https://github.com/contao/news-bundle/blob/master/src/Resources/contao/classes/News.php#L249)

[news_categories](https://github.com/codefog/contao-news_categories/blob/master/classes/News.php#L298)

**Comment by qzminski** [comment]
Fixed in 2cc14e7. Please update your version to 2.8.1.
